version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
    ports:
        - '5438:5432'

